# Generated by Django 5.1.6 on 2025-02-12 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='district',
        ),
        migrations.RemoveField(
            model_name='suboffice',
            name='head_office',
        ),
        migrations.AddField(
            model_name='department',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtapost.state'),
        ),
        migrations.AddField(
            model_name='office',
            name='office_id',
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
        migrations.AddField(
            model_name='office',
            name='tehsil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dtapost.tehsil'),
        ),
        migrations.AddField(
            model_name='suboffice',
            name='tehsil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dtapost.tehsil'),
        ),
        migrations.AddField(
            model_name='suboffice',
            name='upper_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtapost.office'),
        ),
    ]
