# Generated by Django 5.1.6 on 2025-02-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0002_remove_department_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('cadre', 'Cadre'), ('ex-cadre', 'Ex-Cadre')], default=None, max_length=20),
        ),
    ]
