# Generated by Django 5.1.6 on 2025-02-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0003_post_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='head_office',
        ),
        migrations.AddField(
            model_name='office',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dtapost.department'),
        ),
    ]
