# Generated by Django 5.1.6 on 2025-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0004_remove_office_head_office_office_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='office_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
