# Generated by Django 5.1.6 on 2025-02-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0005_alter_office_office_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='tehsil',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtapost.tehsil'),
        ),
    ]
