# Generated by Django 5.1.6 on 2025-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0006_alter_office_tehsil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='tehsil',
        ),
        migrations.AddField(
            model_name='office',
            name='place',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
