# Generated by Django 5.1.6 on 2025-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0007_remove_office_tehsil_office_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
