# Generated by Django 5.1.6 on 2025-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0008_alter_office_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeID',
            field=models.CharField(default=9, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='link_number',
            field=models.IntegerField(default=9, max_length=7),
            preserve_default=False,
        ),
    ]
