# Generated by Django 5.1.6 on 2025-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0009_employee_employeeid_employee_link_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='join_date',
            new_name='currentOffice_join_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='join_post',
            new_name='current_post',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='apo_posting',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='join_office',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='retire_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
