# Generated by Django 5.1.6 on 2025-03-16 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0011_alter_employee_link_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='office_id',
            new_name='office_number',
        ),
        migrations.RemoveField(
            model_name='office',
            name='department',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_name',
        ),
        migrations.AddField(
            model_name='office',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dtapost.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='tehsil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dtapost.tehsil'),
        ),
        migrations.CreateModel(
            name='OfficeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtapost.department')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='office',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dtapost.officename'),
            preserve_default=False,
        ),
    ]
