# Generated by Django 5.1.6 on 2025-03-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0012_rename_office_id_office_office_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officename',
            name='office_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='officename',
            unique_together={('office_name', 'department')},
        ),
    ]
