# Generated by Django 5.1.6 on 2025-03-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0014_alter_post_options_post_post_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
