# Generated by Django 5.1.6 on 2025-03-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0015_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('post_number', 'in_office')},
        ),
    ]
