# Generated by Django 5.1.6 on 2025-03-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtapost', '0016_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
    ]
